### PR TITLE
Fixed filetype error and typo

### PR DESCRIPTION
**Pull request by Reyshyram**

### CODE REVIEW

**Comment by CarloCattano** [comment]
Done already but thanks :-)

**Comment by Reyshyram** [comment]
It's not though?
`os.system(f"grim -type jpeg -q 50 /tmp/workspace{current_workspace}.jpgi")`
is not correct

**Comment by CarloCattano** [comment]
thanks for checking , I just didnt push or was in a detached head for some reason

**Comment by Reyshyram** [comment]
Looking at the grim man page, the option to change the type of the file is -t and not -type, is -type ok at the line 32?

**Comment by CarloCattano** [comment]
Right ! Thats what you meant , I thought you were talking about the extra ```i```
Thanks again

**Comment by Reyshyram** [comment]
I was talking about both, sorry for not being clear

**Pull request closed without merging**
