### PR TITLE
Add the possibility to change colors, and improve README

### PR DESCRIPTION
**Pull request by Reyshyram**

### CODE REVIEW

**Comment by Reyshyram** [comment]
I haven't noticed a difference of latency, I hope this pr is okay

**Comment by CarloCattano** [comment]
This is an awesome PR , I was also going in this direction so it is very apretiated.
However I do get invalid filetype :
```bash
invalid filetype
/home/carlo/test/workspacer
/home/carlo/test/workspacer/colors.conf
````
those are the paths printed and they seem correct, not really sure why it fails to read the file for me

**Comment by Reyshyram** [comment]
I will look into that

**Comment by Reyshyram** [comment]
May be because of confusion between png and jpeg files

**Comment by CarloCattano** [comment]
oh , then thats on my side sorry ! Im merging yours now

**Comment by Reyshyram** [comment]
Thanks!

**Comment by CarloCattano** [comment]
thanks to you !

**Pull request merged**
